name: Publish to PyPI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-n-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment: pip
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies explicitly
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build


      - name: PyPI Poetry Publish
          # You may pin to the exact commit or the version.
          # uses: code-specialist/pypi-poetry-publish@ec93221fb6b8d9d7f2e1e4866840a5df2f8588e3
          uses: code-specialist/pypi-poetry-publish@v1.2
          with:
            # Python Version
            PACKAGE_DIRECTORY: # optional, default is ./
            # Password for the user to publish to PyPI. May also be a Token - requires the `PUBLISH_REGISTRY_USERNAME` to be `__token__`
            PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
